name:                Net-GPSD
version:             0.17
version_from:        lib/Net/GPSD.pm
abstract:            Provides a perl interface to the gpsd daemon.
license:             perl
distribution_type:   module
requires:     
    vars:                          0
    strict:                        0
    IO::Socket:                    0
